name: Copycat
on:
    push:
        branches: [ main ]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: /tokens/tokens.json
        dst_path: /.
        dst_owner: elvism16
        dst_repo_name: tokenized-app
        dst_branch: main
        src_branch: main
        clean: true
        src_wiki: false
        dst_wiki: false
        username: elvism16
        email: elvis.m16@gmail.com
            
