name: Copycat
on:
    push:
        branches: [ main ]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
    - uses: actions/checkout@v2.3.4
    - uses: GuillaumeFalourd/copy-push-files@v1
      with:
          source_files: tokens/tokens.json
          remote_repository: https://github.com/elvism16/tokenized-app
          access_token: ${{ secrets.ACCESS_TOKEN }}

            
