name: Copy To Repo
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy files to another repository
        # You may pin to the exact commit or the version.
        # uses: nkoppel/push-files-to-another-repository@993c4b2dae204519735dd914c24dd6f1d2acd24d
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          # API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-files: 'tokens/'
          destination-username: 'elvism16'
          destination-repository: 'tokenized-app'
          destination-branch: main
          commit-email: 'elvis_m16@gmail.com'
          commit-username: 'elvism16'
