name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
                               
    strategy:
      matrix:
        node-version: [16.x]
        
        
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.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 }}
        with:
          source-directory: 'tokens'
          destination-github-username: 'mastermucha'
          destination-repository-name: 'tokenized-app'
          user-email: elvis.m16@gmail.com
          target-branch: main
